language: php
os: linux

matrix:
  include:
    - php: 7.4
      env: SYMFONY_REQUIRE=4.*
    - php: 7.4
      env: SYMFONY_REQUIRE=5.*
    - php: 8.0
      env: SYMFONY_REQUIRE=4.*
    - php: 8.0
      env: SYMFONY_REQUIRE=5.*

before_install:
  - composer global require --no-progress --no-scripts --no-plugins symfony/flex

install:
  - composer update --prefer-dist --no-progress --prefer-lowest

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - composer run-script tests

after_success:
  - mv ./coverage/clover.xml ./clover.xml
  - ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT
