language: php

php:
  - 7.3
  - 7.4

install:
  - composer install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - composer run-script tests

after_success:
  - mv ./coverage/clover.xml ./clover.xml
  - ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT